//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.19 at 05:05:36 PM MSK 
//


package com.example.candies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ingredients complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ingredients">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fructose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaniline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chocolate-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ingredients", propOrder = {
    "water",
    "sugar",
    "fructose",
    "vaniline",
    "chocolateType"
})
public class Ingredients {

    @XmlElement(required = true)
    protected String water;
    @XmlElement(required = true)
    protected String sugar;
    @XmlElement(required = true)
    protected String fructose;
    @XmlElement(required = true)
    protected String vaniline;
    @XmlElement(name = "chocolate-type", required = true)
    protected String chocolateType;

    /**
     * Gets the value of the water property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWater(String value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSugar(String value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFructose(String value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the vaniline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVaniline() {
        return vaniline;
    }

    /**
     * Sets the value of the vaniline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVaniline(String value) {
        this.vaniline = value;
    }

    /**
     * Gets the value of the chocolateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChocolateType() {
        return chocolateType;
    }

    /**
     * Sets the value of the chocolateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChocolateType(String value) {
        this.chocolateType = value;
    }

}
